version: '3'
services:
  api:
    build:
      context: ./accenture-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433

  frontend:
    build:
      context: ./accenture-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - api
